Telecominfraproject/wlan-cloud-ucentralgw-ui

package-lock.json, package.json, src/components/InterfaceStatistics/containers/DeviceStatisticsChart/index.js, src/components/InterfaceStatistics/containers/DeviceStatisticsChart/index.module.scss, src/components/InterfaceStatistics/containers/StatisticsChartList/index.js, src/components/InterfaceStatistics/index.js, src/layout/Footer/index.js
-rx_bytes are now truly converted to KBs
-Refreshing stats should no longer scroll up the page
-Double renders should also not be happening anymore
=> Fixes for Interface Stats Component

.env, README.md, package-lock.json, package.json, public/config.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/ConfirmFooter/index.js, src/components/DeleteLogModal/index.js, src/components/DeleteLogModal/index.module.scss, src/components/DeviceHealth/index.js, src/components/DeviceHealth/index.module.scss, src/components/DeviceLogs/index.js, src/components/DeviceLogs/index.module.scss, src/components/InterfaceStatistics/containers/StatisticsChartList/index.js, src/config.json, src/layout/Footer/index.js, src/layout/Sidebar/index.module.scss, src/pages/LoginPage/index.js
-We can now choose to delete device logs and healtchecks up to a date chosen by the user (#4)
-The config.json file (in the solution the public/config.json file, in production it would be at the root) now contains the DEFAULT_GATEWAY_URL and ALLOW_GATEWAY_CHANGE values. These can be both modified pre-build and post-build. In addition, it gives the website administrators the possibility of modifying it post-deployment.
-Sidebar imp size is now fixed, will help render times
=> Option to delete logs and healthchecks, modified how the default config is evaluated

src/components/InterfaceStatistics/StatisticsChartList.js
=> Using smooth lines for stats line graph

package-lock.json, package.json, src/components/DeviceListTable/index.js
=> Version 2.4.2

package-lock.json, package.json, src/components/DeviceListTable/index.js
Reverts Telecominfraproject/wlan-cloud-ucentralgw-ui#68
=> Revert "Version 2.4.2"

package-lock.json, package.json, src/components/DeviceFirmwareModal/index.js, src/components/DeviceListTable/index.js, src/pages/FirmwareListPage/index.js
- Fixing offsets for table queries (https://telecominfraproject.atlassian.net/browse/WIFI-5780)
=> Version 2.4.3

helm/templates/_helpers.tpl, helm/templates/ingress.yaml, helm/values.yaml
=> [WIFI-1998] Add: gracefull ingress deprecationush

helm/values.yaml
=> [WIFI-7825] Chg: use ClusterIP for service by default

public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/TelemetryModal/index.js
Please refer to the Jira ticket.
=> WIFI-7947: Telemetry: Add lifetime and kafka/websocket options

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/WifiAnalysis/index.js, src/components/WifiScanModal/index.js
=> [WIFI-9773] Wifi Scan request sometimes stalling

package-lock.json, package.json, src/components/TelemetryModal/index.js
=> [WIFI-9921] Telemetry now only showing selected types when receiving messages

package-lock.json, package.json, src/components/DeviceSearchBar/Input.js, src/components/DeviceSearchBar/index.js, src/components/WifiScanModal/index.js, src/contexts/WebSocketProvider/index.js, src/utils/helper.js
- WifiScan is now always sending all IE options
- Removed WifiScan IE selection
- Fixed crash on rare endpoint JSON corruption
=> [WIFI-10259] WifiScan now sending all IE options

package-lock.json, package.json, src/components/InterfaceStatistics/LatestStatisticsModal.js, src/components/InterfaceStatistics/StatisticsChartList.js, src/contexts/WebSocketProvider/utils.js
=> [WIFI-10515] Crash fix when receiving corrupted statistics

package-lock.json, package.json, src/components/NetworkDiagram/Graph.js, src/components/NetworkDiagram/index.js
=> [WIFI-10548] Network diagram now showing all associations

Dockerfile
=> [WIFI-10414] Fix: vulnerable NodeJS image

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/pages/DevicePage/index.js
=> [WIFI-10832] Redirecting on invalid/not found serial numbers on device page

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/BlinkModal/index.js, src/components/ConfigureModal/index.js, src/components/DeviceActionCard/index.js, src/components/DeviceFirmwareModal/index.js, src/components/EventQueueModal/index.js, src/components/FactoryResetModal/index.js, src/components/RebootModal/index.js, src/components/TelemetryModal/index.js, src/components/TraceModal/index.js, src/components/WifiScanModal/index.js
=> [WIFI-10850] Error descriptions on command failures

src/components/InterfaceStatistics/StatisticsChartList.js
=> [WIFI-10857] Fixed display when there are no entries

package-lock.json, package.json, src/components/CommandHistory/index.js
=> [WIFI-10894] Status column added to command history

package-lock.json, package.json, src/contexts/WebSocketProvider/index.js, src/contexts/WebSocketProvider/utils.js, src/layout/Devices.js, src/layout/Sidebar/index.js, src/layout/Sidebar/index.module.scss, src/layout/index.js, src/utils/helper.js
=> [WIFI-10904] Connection statistics on the sidebar

src/contexts/WebSocketProvider/index.js, src/layout/Devices.js
=> [WIFI-10904] Websocket more resilient in case of disconnection

package-lock.json, package.json, src/components/DeviceSearchBar/index.js, src/contexts/WebSocketProvider/index.js
=> [WIFI-10931] Fixed using ws websockets when using http GW endpoint

package-lock.json, package.json, src/hooks/Network/Endpoints.ts, src/pages/SystemPage/index.tsx
=> [WIFI-11392] Refetch all endpoints on System page

index.html
=> [WIFI-11455] Fix to fetch env file for docker build

Dockerfile
=> [WIFI-11451] Fix: Dockerfile

docker-entrypoint.d/40-generate-config.sh, helm/values.yaml
=> [WIFI-11464] Fix: entrypoint script

package-lock.json, package.json, src/components/Modals/ConfigureModal/index.tsx
=> [WIFI-11563] Added import file button to configure modal

package-lock.json, package.json, src/components/Modals/TelemetryModal/index.tsx, src/pages/Device/Details.tsx, src/pages/Device/StatisticsCard/ViewLastStatsModal.tsx, src/pages/Device/ViewCapabilitiesModal.tsx, src/pages/Device/ViewConfigurationModal.tsx
=> [WIFI-11566] Fixed uses of useClipboard

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/DatePickers/DatePickerInput/index.tsx, src/components/DatePickers/DateTimePicker/index.tsx, src/hooks/Network/ApiKeys.ts, src/pages/Profile/ApiKeys/Table/Actions.tsx, src/pages/Profile/ApiKeys/Table/AddButton.tsx, src/pages/Profile/ApiKeys/Table/DescriptionCell.tsx, src/pages/Profile/ApiKeys/Table/ExpiresOnField.tsx, src/pages/Profile/ApiKeys/Table/index.tsx, src/pages/Profile/ApiKeys/Table/useApiKeyTable.tsx, src/pages/Profile/ApiKeys/index.tsx, src/pages/Profile/Layout.tsx
=> [WIFI-11543] Added API keys to profile page

src/components/Modals/EventQueueModal/index.tsx, src/hooks/Network/Commands.ts
=> [WIFI-11545] Fixed event queue API

package-lock.json, package.json, src/contexts/ControllerSocketProvider/useStore.ts, src/pages/Devices/ListCard/DeviceSearchBar.tsx
=> [WIFI-11584]  Reconnecting WebSocket when focusing on search bar

package-lock.json, package.json, src/pages/Device/WifiAnalysis/AssocationsTable.tsx, src/pages/Device/WifiAnalysis/RadiosTable.tsx
=> [WIFI-11594] Fixed hidden columns in wifi analysis

package-lock.json, package.json, src/pages/Device/index.tsx
=> [WIFI-11700] Fix for non-lowercase serial numbers in device page

package-lock.json, package.json, src/hooks/Network/Statistics.ts, src/pages/Device/StatisticsCard/index.tsx, src/pages/Device/StatisticsCard/useStatisticsCard.ts
=> [WIFI-11251] Now fetching device statistics in batches of 100

package-lock.json, package.json, src/hooks/Network/Devices.ts, src/pages/Devices/ListCard/index.tsx
=> [WIFI-11728] Added 6G associations to device table

package-lock.json, package.json, src/contexts/ControllerSocketProvider/hooks/Commands/useDeviceSearch.ts, src/pages/Device/StatisticsCard/useStatisticsCard.ts, src/pages/Device/WifiAnalysis/AssocationsTable.tsx, src/pages/Device/WifiAnalysis/RadiosTable.tsx, src/pages/Device/WifiAnalysis/index.tsx, src/pages/Devices/ListCard/DeviceSearchBar.tsx
=> [WIFI-11749] Limiting device search bar input text length

package-lock.json, package.json, src/pages/Device/LogsCard/CommandHistory/Modal.tsx, src/pages/Device/StatisticsCard/ViewLastStatsModal.tsx, src/pages/Device/ViewCapabilitiesModal.tsx, src/pages/Device/ViewConfigurationModal.tsx
=> [WIFI-11753] Fixed JSON displays to deal with wide strings

package-lock.json, package.json, src/pages/Firmware/Dashboard/AverageFirmwareAge.tsx
=> [WIFI-11868] Fixed FMS dashboard average age

package-lock.json, package.json, src/components/Modals/ScriptModal/ResultDisplay.tsx, src/pages/Device/LogsCard/CommandHistory/ResultModal/DownloadScriptButton.tsx, src/pages/Device/LogsCard/CommandHistory/ResultModal/DownloadTraceButton.tsx
=> [WIFI-11542] Script result display and download fixes

package-lock.json, package.json, src/layout/Navbar/index.tsx
=> [WIFI-11873] Navbar menu hidden by device page bar fix

package-lock.json, package.json, src/components/Modals/TelemetryModal/index.tsx
=> [WIFI-11874] Telemetry results now using full page height

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/models/Device.ts, src/pages/Device/RestrictionsCard/index.tsx, src/pages/Device/Wrapper.tsx
=> [WIFI-11958] Device restriction details display

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/pages/Devices/ListCard/index.tsx
=> [WIFI-11936] Serial number in device table now real link

package-lock.json, package.json, src/hooks/Network/Statistics.ts, src/pages/Device/StatisticsCard/useStatisticsCard.ts
=> [WIFI-10957] Updated statistics to use counters-aggregate if available

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/Buttons/DeviceActionDropdown/index.tsx, src/components/Modals/RebootModal/index.tsx, src/pages/Device/Wrapper.tsx, src/pages/Devices/ListCard/Actions.tsx, src/pages/Devices/ListCard/index.tsx
=> [WIFI-12031] Added confirmation modal to reboot process

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/Modals/GenericModal/ModalHeader/index.tsx, src/components/Modals/Modal/index.tsx, src/hooks/Network/Firmware.ts, src/hooks/Network/Users.ts, src/pages/LoginPage/LoginForm.tsx, src/pages/UsersPage/Table/ActionsDropdown.tsx, src/pages/UsersPage/Table/EditUserModal/Form.tsx, src/pages/UsersPage/Table/EditUserModal/index.tsx, src/pages/UsersPage/Table/index.tsx
=> [WIFI-12223] User table state fix, with label correction and API logic update

package-lock.json, package.json, src/pages/Device/StatisticsCard/InterfaceChart.tsx
=> [WIFI-12226] Interface stats Y-axis now only 2 decimals or less

package-lock.json, package.json, src/hooks/Network/Firmware.ts
=> [WIFI-11239] Now sending signature on firmware upgrade as URL param

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/components/Modals/FirmwareUpgradeModal/index.tsx, src/components/Modals/ScriptModal/Form.tsx, src/components/Modals/ScriptModal/index.tsx, src/pages/Device/RestrictionsCard/index.tsx, src/pages/Device/Wrapper.tsx, src/pages/Devices/Blacklist/CreateModal.tsx
=> [WIFI-12270] Now displaying information related to restricted device in dev mode

package-lock.json, package.json, public/locales/de/translation.json, public/locales/en/translation.json, public/locales/es/translation.json, public/locales/fr/translation.json, public/locales/pt/translation.json, src/hooks/Network/Firmware.ts, src/pages/Firmware/List/Modal.tsx, src/pages/Firmware/List/UpdateDbButton.tsx, src/pages/Firmware/List/index.tsx
=> [WIFI-12285] Add support for FMS database refreshes

.gitignore, package.json, src/layout/Navbar/index.tsx
Fixed Overlapping issue with GW UI Navbar overlap on Device Details page.
[JIRA URL](https://telecominfraproject.atlassian.net/browse/WIFI-13097)
=> [WIFI-13097] Fixed issue with Navbar Overlap

package.json
Release 3.2 version update.
https://telecominfraproject.atlassian.net/browse/WIFI-14165
=> WIFI-14165: release 3.2 version update

package.json
Version update on main.
https://telecominfraproject.atlassian.net/browse/WIFI-14165
=> fix: release 3.2.1 version update

package.json
Release version 4.0.0 update.
https://telecominfraproject.atlassian.net/browse/WIFI-14521
=> WIFI-14521: fix: Version update - release 4.0.0
